const products = [
  {
    id: 1,
    subject: 'Garden',
    price: 100,
    space: 3,
    image: 'img/Garden.jpg',
    cartquantity: 0,
  },
  {
    id: 2,
    subject: 'Baby',
    price: 50,
    space: 6,
    image: 'img/Baby.jpg',
    cartquantity: 0,
  },
  {
    id: 3,
    subject: 'Friends',
    price: 200,
    space: 2,
    image: 'img/Friends.jpg',
    cartquantity: 0,
  },
  {
    id: 4,
    subject: 'Office',
    space: 7,
    image: 'img/Office.jpg',
    cartquantity: 0,
  },
  {
    id: 5,
    subject: 'Home',
    price: 30,
    space: 20,
    image: 'img/Home.jpg',
    cartquantity: 0,
  },
  {
    id: 6,
    subject: 'Library',
    price: 45,
    space: 35,
    image: 'img/Library.jpg',
    cartquantity: 0,
  },
  {
    id: 7,
    subject: 'Car',
    price: 90,
    space: 7,
    image: 'img/Car.jpg',
    cartquantity: 0,
  },
  {
    id: 8,
    subject: 'Animal',
    price: 200,
    space: 6,
    image: 'img/animal.jpg',
    cartquantity: 0,
  },
  {
    id: 9,
    subject: 'Swimming',
    price: 150,
    space: 9,
    image: 'img/Swimming.jpg',
    cartquantity: 0,
  },
  
];